#!/bin/sh
if [ -f '/etc/opkg/distfeeds.conf' ]; then
    patterns_to_remove="qmodem istore nss"
    temp_file=$(mktemp)
    while IFS= read -r line; do
        remove=0
        for pattern in $patterns_to_remove; do
            if echo "$line" | grep -q "_${pattern}"; then
                remove=1
                break
            fi
        done
        if [ "$remove" -eq 0 ]; then
            echo "$line" >> "$temp_file"
        fi
    done < /etc/opkg/distfeeds.conf
    cat "$temp_file" > /etc/opkg/distfeeds.conf
    rm "$temp_file"
fi

exit 0