#!/bin/sh

. /etc/init.d/smp_affinity

for IFACE in /sys/class/net/*; do
    INTERFACE=$(basename "$IFACE")
    IFNAME_PREFIX="${INTERFACE%%[0-9]*}"

    if [ "$INTERFACE" != "eth01" ] && [ "$INTERFACE" != "eth11" ] && \
       { [ "$IFNAME_PREFIX" = "usb" ] || [ "$IFNAME_PREFIX" = "wwan" ] || [ "$IFNAME_PREFIX" = "rmnet" ] || [ "$IFNAME_PREFIX" = "eth" ] || [ "$IFNAME_PREFIX" = "rmnet_mhi" ]; }; then
        echo f > "/sys/class/net/${INTERFACE}/queues/rx-0/rps_cpus"
    fi
    if [ "$IFNAME_PREFIX" = "rmnet_mhi" ]; then
        setaffinity  'mhi'         3 1
        setaffinity  'mhi'         3 2
        setaffinity  'mhi'         3 3
        setaffinity  'mhi'         3 4
    fi
done